import { Merriweather } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300","400","700","900"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={merriweather.className}>
      <Header />
        {children}
      </body>
    </html>
  );
}
